### ISSUE TITLE
No file to download

### ISSUE THREAD

**Issue by mountaincastle47** [tsgsOFFICIAL/CSGO-AutoAccept.exe#2]
HELP!

**Comment by tsgsOFFICIAL** [comment]
Hey have you read the [README](../#where-can-i-download-this), specifically the "**Where can I download this?**" section?

If you are still having troubles, I'd love to help you out.

**Comment by tsgsOFFICIAL** [comment]
I forgot to update the releases section, my apologies.

**Comment by mountaincastle47** [comment]
oh the download wasn't compatible with idm lol

**Comment by tsgsOFFICIAL** [comment]
I've marked this issue as completed, if there is any issues, please don't hesitate to get in touch again, either here or in my [Discord Server](https://discord.gg/Cddu5aJ).

**Comment by mountaincastle47** [comment]
> I've marked this issue as completed, if there is any issues, please don't hesitate to get in touch again, either here or in my [Discord Server](https://discord.gg/Cddu5aJ).

just did on the discord!
